appName:
  app: nginx-prod
replicas: 4
container:
  name: nginx-cont
  image: nginx:1.22.1
  port: 80
  env: 
    - name: POSTGRES_USER
      value: postgres-prod
    - name: POSTGRES_PASSWORD
      value: postgres_123
    - name: POSTGRES_DATABASE
      value: prod_db