appName:
  app: nginx-stagging
replicas: 2
container:
  name: nginx-cont
  image: nginx:1.22.1
  port: 80 
  env: 
    - name: POSTGRES_USER
      value: postgres-stag
    - name: POSTGRES_PASSWORD
      value: postgres_123
    - name: POSTGRES_DATABASE
      value: stag_db
