apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: my-nginx-lbl
spec:
  containers:
  - name: nginx-cont
    image: nginx:latest
    ports:
      - containerPort: 80


# kubectl apply -f nginx-pod.yaml 
# kubectl delete -f nginx-pod.yaml 
# kubectl delete pod/my-nginx-pod 
# kubectl get pod 
# kubectl get pod -o wide 
# kubectl describe pod/my-nginx-pod
# kubectl logs pod/my-nginx-pod