apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.app }}-dpl
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName.app }}
    spec:
      containers:
      {{- with .Values.container }}
      - name: {{ .name }}
        image: {{ .image }}
        ports:
        - containerPort: {{ .port }}
      {{- end }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"