apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.app }}-dpl
spec:
  replicas: {{ .Values.replicas }}
  {{- include "dpl-selector" . }}  
    spec:
      affinity: 
      {{- toYaml .Values.affinity  | nindent 7 }}

      containers:
      {{- with .Values.container }}
      - name: {{ .name }}
        image: {{ .image }}
        ports:
        - containerPort: {{ .port }}
        {{- if .volumeMounts }}
        volumeMounts: 
          {{- toYaml .volumeMounts | nindent 8 }}
        {{- end  }}
        env: 
      {{- range .env }}
          - name: {{ .name }}
            value: {{ .value }}
      {{- end }}
        
        
      {{- end }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
    {{- include "volume-config" . }}