[all:vars]
ansible_user=kk
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3.10
[local]
localhost ansible_connection=local

[masters]
master02 ansible_host=34.87.15.74
master03 ansible_host=34.126.105.82


[workers]
worker01 ansible_host=34.150.61.90
worker02 ansible_host=34.92.124.179
